name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: '3.10'
            toxenv: py310,lint,pytype
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox
      - name: tox
        run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
      